apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejsapp
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/CNCF-Lahore/Sandbox-Example-Projects
    targetRevision: HEAD
    path: nodejsapp
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
